name: Blog
author: Poulami-Sarkar
baseurl: /blog
description: GSoC Red Hen Lab
github: http://www.github.com/Bengali-Hindi-OCR
twitter: https://twitter.com/0Kira10
facebook: http://www.facebook.com
linkedin: https://www.linkedin.com/in/poulami-sarkar/
email: poulamisarkar101@gmail.com
location: Bangalore India
disqus: diqus-username

##Make sure to edit the above fields, especially for disqus.


highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: ["tables"]

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

theme: jekyll-theme-cayman
