# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "Blog"
description: > # this means to ignore newlines until "email:"
   Red Hen Lab bengali and Hindi OCR

email: poulamisarkar101@gmail.com
#blog logo
logo: "/assets/images/df_logo.jpg"
float_logo: true # true, false (default)

# blog cover
cover: "/assets/images/cA4aKEIPQrerBnp1yGHv_IMG_9534-3-2.jpg"

name: 'Poulami Sarkar'
author: 'Poulami Sarkar'
#author_image: "/assets/images/author.jpg"

paginate:	5

url: "https://poulami-sarkar.github.io" # the base hostname & protocol for your site
baseurl: "/blog"
#used to display twitter cards
twitter_handle: '@0Kira10'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

#google_analytics: UA-XXXXX-X

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/0Kira10
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="
     
  - icon:	github
    url:	https://github.com/Poulami-Sarkar
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:
    
  - icon:	linkedin
    url:	https://scholar.google.com/citations?user=XLLzkTgAAAAJ&hl=en#
    desc:	Look me up on google scholar
    share_url:
    share_title:
    share_link:    

  - icon:	google
    url:	https://scholar.google.com/citations?user=XLLzkTgAAAAJ&hl=en#
    desc:	Look me up on google scholar
    share_url:
    share_title:
    share_link:
