# Site settings
## Change the values as needed.
title: "GSoC Blog"
email: poulamisarkar101@gmail.com
description: "GSoC Blog"
baseurl: "/blog"
url: "https://poulami-sarkar.github.io/blog/"
title_description: "This project implements OCR for television news from Bengali and Hindi news channels. I am using OpenCV along with a pre-trained tensorflow model called EAST(An Efficient and Accurte Scene Test detector) for detecting ROI (Regions of interest) from the news videos. Then the detected ROIs are extracted and OCR, implemented using tesseract 4.0 is used to exract the text."
keywords: ""
paginate: 5
paginate_path: "page:num"
# Build settings
markdown: kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: :compressed
links:
  facebook: 
  twitter: 0Kira10
  email: poulamisarkar101@gmail.com
  github: https://github.com/Poulami-Sarkar/Bengali-Hindi-OCR
exclude:
  - bower_components
  - README.md
full_name: Brijesh

##set this to enable disqus commenting
disqus: bitwiser

##set this to enable google analytics
#ga_id: analyticsID
#ga_domain: bitwiser.in
