# Site settings
## Change the values as needed.
title: GSoC Blog
email: poulamisarkar101@gmail.com
description: "Bengali and Hindi OCR"
keywords: ""
#url: "http://bitwiser.in/bitwiser-material" # the base hostname & protocol for your site
url: "https://poulami-sarkar.github.io/blog" # the base hostname & protocol for your site
baseurl: "/blog" # the subpath of your site, e.g. /blog/
paginate: 5
paginate_path: "page:num"
# Build settings
markdown: kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: :compressed
links:
  facebook: 
  twitter: 0Kira10
  email: poulamisarkar101@gmail.com
  github: https://github.com/Poulami-Sarkar/Bengali-Hindi-OCR
exclude:
  - bower_components
  - README.md
full_name: Brijesh

##set this to enable disqus commenting
disqus: bitwiser

##set this to enable google analytics
#ga_id: analyticsID
#ga_domain: bitwiser.in
